### ISSUE TITLE
The mp3 volume is too low to hear.

### ISSUE THREAD

**Issue by wangzongming** [pschatzmann/arduino-liblame#12]
🌹Hello, can you help me to see how to change the code?
I want to convert pcm to mp3 and send it to the server. It worked.
However, the mp3 file saved in the server cannot be heard when playing, and the sound can be heard after the volume is amplified by ffmpeg.
Is there any way to amplify the volume in the following code?

```
loop(){ 
        i2s_read(MIC_i2s_num, (void *)diy_wakeup_sample_buffer, sizeof(diy_wakeup_sample_buffer), &diy_wakeup_bytes_read, portMAX_DELAY);
        esp_ai_mp3_encoder.write(diy_wakeup_sample_buffer, sizeof(diy_wakeup_sample_buffer));
}
```

I've tried the following, but it doesn't sound very effective.
```
i2s_read(MIC_i2s_num, (void *)diy_wakeup_sample_buffer, sizeof(diy_wakeup_sample_buffer), &diy_wakeup_bytes_read, portMAX_DELAY); 
for (size_t i = 0; i < sizeof(diy_wakeup_sample_buffer) / 2; i++) 
{ 
     diy_wakeup_sample_buffer[i] = diy_wakeup_sample_buffer[i] * 128;
}

esp_ai_mp3_encoder.write(diy_wakeup_sample_buffer, sizeof(diy_wakeup_sample_buffer));
```

**Comment by pschatzmann** [comment]
I suggest to use the [AudioTools](https://github.com/pschatzmann/arduino-audio-tools); follow the [advice given under Audio Source](https://github.com/pschatzmann/arduino-audio-tools/wiki/It's-not-working).
This let's you decide how much [you can ampltiy](https://github.com/pschatzmann/arduino-audio-tools/wiki/Volume-Control). You can even implement a dynamic amplification by checking the actual volume using a VolumeMeter.

**Comment by wangzongming** [comment]
Thank you for your prompt reply.
